name: Create zip

on: workflow_dispatch

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15'
          cache: npm

      - name: Setup NPM cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          npm run build
          node docker/pack

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: directus
          path: ./dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: directus-2
          path: dist